### ISSUE TITLE
Need to create a loading page and pool image resources

### ISSUE THREAD

**Issue by nateonguitar** [nateonguitar/TS2DGameEngine#21]
If we create 1000 soldiers we create an Image for each one, but we should really just create a single image for each one we will use on game launch (or really on level/stage launch).

Here's a video example of the problem in action:
https://youtu.be/nRgYm7Gwqe0

(actual issue demonstrated at 43 seconds)

**Comment by NasserDos** [comment]
So, I tried to have the images shared throughout the life of a controller. It didn't seem to make a huge difference as far as I could see. I didn't get a chance to stress test it. 

It was somewhat troublesome to hunt down all the image "set"ing and src "set"ing. (maybe we can have this cleaned up by always setting the image of an object and let them change the object they're pointing to instead to avoid dealing with different type of "set" image vs "set" image.src .
